//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBooking.Models
{
    using System;
    
    public partial class CT_BCDOANHSO
    {
        public int CTBC_ID { get; set; }
        public Nullable<int> BC_ID { get; set; }
        public Nullable<int> TaiXeID { get; set; }
        public Nullable<int> TyLe { get; set; }
        public Nullable<int> TongGiaTri { get; set; }
    
        public virtual BC_DOANHSO BC_DOANHSO { get; set; }
        public virtual TAIXE TAIXE { get; set; }
    }
}
