//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DATXE
    {
        public int CT_DatXeID { get; set; }
        public Nullable<int> DatXeID { get; set; }
        public Nullable<int> XeID { get; set; }
        public Nullable<int> TaiXeID { get; set; }
        public Nullable<int> DDiemID { get; set; }
        public Nullable<int> KhID { get; set; }
        public Nullable<int> DVuID { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DATXE DATXE { get; set; }
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual DICHVU DICHVU { get; set; }
        public virtual TAIXE TAIXE { get; set; }
        public virtual XE XE { get; set; }
    }
}
