//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA_PHANHOI
    {
        public int ID { get; set; }
        public Nullable<int> DatXeID { get; set; }
        public string DanhGia { get; set; }
        public string PhanHoi { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual DATXE DATXE { get; set; }
    }
}
