//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATXE()
        {
            this.CT_DATXE = new HashSet<CT_DATXE>();
            this.DANHGIA_PHANHOI = new HashSet<DANHGIA_PHANHOI>();
            this.HOADONs = new HashSet<HOADON>();
            this.PHIEU_HUYDATXE = new HashSet<PHIEU_HUYDATXE>();
        }
    
        public int DatXeID { get; set; }
        public Nullable<int> XeID { get; set; }
        public Nullable<int> DDiemID { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DATXE> CT_DATXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA_PHANHOI> DANHGIA_PHANHOI { get; set; }
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual XE XE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_HUYDATXE> PHIEU_HUYDATXE { get; set; }
    }
}
