//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIADIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIADIEM()
        {
            this.CT_DATXE = new HashSet<CT_DATXE>();
            this.DATXEs = new HashSet<DATXE>();
        }
    
        public int DDiemID { get; set; }
        public string DiemXuatPhat { get; set; }
        public string DiemDen { get; set; }
        public string QuanDi { get; set; }
        public string QuanDen { get; set; }
        public Nullable<double> GiaTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DATXE> CT_DATXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATXE> DATXEs { get; set; }
    }
}
