//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int HoaDonID { get; set; }
        public Nullable<int> DatXeID { get; set; }
        public Nullable<int> DVuID { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string PhuongThucThanhToan { get; set; }
    
        public virtual DATXE DATXE { get; set; }
        public virtual DICHVU DICHVU { get; set; }
    }
}
