//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHLAMVIEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHLAMVIEC()
        {
            this.TAIXEs = new HashSet<TAIXE>();
        }
    
        public int LLViecID { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> ThoiGianBD { get; set; }
        public Nullable<int> ThoiGianKT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIXE> TAIXEs { get; set; }
    }
}
