//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBooking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCarBookingEntities : DbContext
    {
        public DBCarBookingEntities()
            : base("name=DBCarBookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BC_DOANHSO> BC_DOANHSO { get; set; }
        public virtual DbSet<CT_BCDOANHSO> CT_BCDOANHSO { get; set; }
        public virtual DbSet<CT_DATXE> CT_DATXE { get; set; }
        public virtual DbSet<DANHGIA_PHANHOI> DANHGIA_PHANHOI { get; set; }
        public virtual DbSet<DATXE> DATXEs { get; set; }
        public virtual DbSet<DIADIEM> DIADIEMs { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHUVUCLAMVIEC> KHUVUCLAMVIECs { get; set; }
        public virtual DbSet<LICHLAMVIEC> LICHLAMVIECs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEU_HUYDATXE> PHIEU_HUYDATXE { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIXE> TAIXEs { get; set; }
        public virtual DbSet<VI_VNS> VI_VNS { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
    }
}
