//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIXE()
        {
            this.CT_BCDOANHSO = new HashSet<CT_BCDOANHSO>();
            this.CT_DATXE = new HashSet<CT_DATXE>();
        }
    
        public int TaiXeID { get; set; }
        public Nullable<int> KhuVucID { get; set; }
        public Nullable<int> LLViecID { get; set; }
        public Nullable<int> XeID { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Sdt { get; set; }
        public string DiaChi { get; set; }
        public Nullable<byte> SoCuocXe { get; set; }
        public Nullable<int> Luong { get; set; }
        public Nullable<bool> TinhTrangHopDong { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BCDOANHSO> CT_BCDOANHSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DATXE> CT_DATXE { get; set; }
        public virtual KHUVUCLAMVIEC KHUVUCLAMVIEC { get; set; }
        public virtual LICHLAMVIEC LICHLAMVIEC { get; set; }
        public virtual XE XE { get; set; }
    }
}
