//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VI_VNS
    {
        public int ViID { get; set; }
        public Nullable<int> KhID { get; set; }
        public Nullable<int> SoDu { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public Nullable<System.DateTime> ThoiGianGiaoDich { get; set; }
        public Nullable<int> SoTienGiaoDich { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
